import { AccountData, ClientAccount } from '@test-npx/api-interfaces';

export const accounts: ClientAccount[] = [
  {
    currency: {
      shortCode: 'USD',
      name: 'US Dollar',
    },
    id: 1,
  },
  {
    currency: { shortCode: 'EUR', name: 'Euro' },
    id: 2,
  },
  {
    currency: { shortCode: 'SGD', name: 'Singapore Dollar' },
    id: 3,
  },
];

export const accountsData: Record<ClientAccount['id'], AccountData> = {
  1: {
    currentBalance: 17929.87,
    transactions: [
      {
        recipient: 'Some fintech client',
        date: new Date('2021-07-22T10:00:00') ,
        txnType: 2,
        contraAmount: 1000.0,
        fxConversionRate: 1.0,
        netAmount: -1000.0,
        txnFee: -15.0,
        fxConversionFee: 0.0,
        amount: -1015.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 16,
      },
      {
        recipient: 'Donald Trump',
        date: new Date('2021-06-21T10:00:00'),
        txnType: 2,
        contraAmount: 12000.0,
        fxConversionRate: 1.0,
        netAmount: -12000.0,
        txnFee: -30.0,
        fxConversionFee: 0.0,
        amount: -12030.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 15,
      },
      {
        recipient: null,
        date: new Date('2021-05-20T10:00:00'),
        txnType: 1,
        contraAmount: 8047.74,
        fxConversionRate: 2.0,
        netAmount: 16095.48,
        txnFee: -15.0,
        fxConversionFee: -80.48,
        amount: 16000.0,
        contraCurrency: { shortCode: 'SGD', name: 'Singapore Dollar' },
        id: 13,
      },
      {
        recipient: 'The show',
        date: new Date('2021-04-30T10:05:00'),
        txnType: 2,
        contraAmount: 2500.0,
        fxConversionRate: 0.4975,
        netAmount: -5025.13,
        txnFee: 0.0,
        fxConversionFee: 0.0,
        amount: -5025.13,
        contraCurrency: { shortCode: 'SGD', name: 'Singapore Dollar' },
        id: 10,
      },
      {
        recipient: 'Whitehouse',
        date: new Date('2021-07-18T10:07:00'),
        txnType: 2,
        contraAmount: 7000.0,
        fxConversionRate: 1.0,
        netAmount: -7000.0,
        txnFee: -30.0,
        fxConversionFee: 0.0,
        amount: -7030.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 7,
      },
      {
        recipient: 'The show',
        date: new Date('2021-07-14T12:00:00'),
        txnType: 1,
        contraAmount: 5015.0,
        fxConversionRate: 1.0,
        netAmount: 5015.0,
        txnFee: -15.0,
        fxConversionFee: 0.0,
        amount: 5000.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 5,
      },
      {
        recipient: 'Donald Trump',
        date: new Date('2021-07-14T10:03:00'),
        txnType: 2,
        contraAmount: 5000.0,
        fxConversionRate: 1.0,
        netAmount: -5000.0,
        txnFee: -30.0,
        fxConversionFee: 0.0,
        amount: -5030.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 4,
      },
      {
        recipient: 'The show',
        date: new Date('2021-07-10T10:00:00'),
        txnType: 1,
        contraAmount: 10015.0,
        fxConversionRate: 1.0,
        netAmount: 10015.0,
        txnFee: -15.0,
        fxConversionFee: 0.0,
        amount: 10000.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 1,
      },
    ],
  },
  2: {
    currentBalance: 2500.0,
    transactions: [
      {
        recipient: '1 (USD)',
        date: new Date('2021-07-30T10:15:00'),
        txnType: 1,
        contraAmount: 5025.13,
        fxConversionRate: 2.01005,
        netAmount: 2500.0,
        txnFee: 0.0,
        fxConversionFee: 0.0,
        amount: 2500.0,
        contraCurrency: { shortCode: 'USD', name: 'US Dollar' },
        id: 12,
      },
    ],
  },
  3: {
    currentBalance: 0.0,
    transactions: [],
  },
};
